{
 "title": "SoftUni - App Monitoring Tools",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Probe Duration Seconds",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Http Status Code ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Http Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "probe_http_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}